name: tz01
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5     
  http: ^0.13.5         
  provider: ^6.0.5      
  shared_preferences: ^2.2.2 
  hive_flutter: ^1.1.0  
  animated_text_kit: ^4.2.2 
  shimmer: ^2.0.0  
  connectivity_plus: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  bloc_test: ^9.1.2
  mockito: ^5.4.0   

flutter:
  uses-material-design: true
